# Generated by Django 4.1 on 2022-08-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=55)),
                ('playlist_vibes', models.CharField(max_length=55)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, max_length=7)),
            ],
        ),
    ]
